### ISSUE TITLE
addon weather ?

### ISSUE THREAD

**Issue by ceeeeb** [dhermanns/rpi-openhab#1]
Hello,

I use addon "org.openhab.binding.weather" with my openhab,

There are a lot of error in openhab.log : 

`javax.servlet.ServletException: File with weather layout 'example.html' does not exist, make sure it is in the layouts folder ./webapps/weather-data/layouts
`

is what I have to copy the weather-data in /home/pi/openhab ??

**Comment by dhermanns** [comment]
Sorry - haven't used it myself. But maybe someone else can help...
